apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "serviceName" . }}
  labels:
    app: {{ template "serviceName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "serviceName" . }}
  template:
    metadata:
      labels:
        app: {{ template "serviceName" . }}
    spec:
      containers:
        - name: {{ template "serviceName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.app }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://bank-manager-postgres:5432/{{ .Values.postgres.postgresDatabase }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.postgres.postgresUsername }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.postgres.postgresPassword }}"