apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-manager-postgres
  labels:
    app: bank-manager-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-manager-postgres
  template:
    metadata:
      labels:
        app: bank-manager-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.postgresDatabase }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.postgresUsername }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.postgresPassword }}"