apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postgresServiceName" . }}
  labels:
    app: {{ template "postgresServiceName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "postgresServiceName" . }}
  template:
    metadata:
      labels:
        app: {{ template "postgresServiceName" . }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.containerPorts.database }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.postgresDatabase }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.postgresUsername }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.postgresPassword }}"