apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresServiceName" . }}
  labels:
    app: {{ template "postgresServiceName" . }}
spec:
  ports:
    - port: {{ .Values.containerPorts.database }}
  selector:
    app: {{ template "postgresServiceName" . }}