apiVersion: v1
kind: Service
metadata:
  name: bank-manager-server
  labels:
    app: bank-manager-server
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30007
  selector:
    app: bank-manager-server