apiVersion: v1
kind: Service
metadata:
  name: bank-manager-server
  labels:
    app: bank-manager
spec:
  type: NodePort
  selector:
    app: bank-manager
  ports:
    - name: bank-manager-app-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007