apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-manager
  template:
    metadata:
      labels:
        app: bank-manager
      annotations:
        service.kubernetes.io/service-name: bank-manager-server
    spec:
      containers:
        - name: bank-manager
          image: bank-manager-server
          imagePullPolicy: "IfNotPresent"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/ee_bankdb
          ports:
            - containerPort: 8080