apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
    - name: postgres-db-port
      protocol: TCP
      port: 5432
      targetPort: 5432