CREATE TABLE IF NOT EXISTS accounts
(
    account_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iban VARCHAR(40),
    balance INTEGER,
    currency VARCHAR(3),
    customer_id INTEGER,
    CONSTRAINT fk_customer_id FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);