CREATE TABLE users (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at TIMESTAMP,
                       modified_at TIMESTAMP,
                       enabled BOOLEAN NOT NULL DEFAULT TRUE,
                       username VARCHAR(255) UNIQUE NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       full_name VARCHAR(255)
);

CREATE TABLE authorities (
             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             user_id INTEGER,
             authority VARCHAR(10),
             CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);